language: node_js
sudo: required
node_js:
  - "6"
  - "node"
services:
  - rabbitmq
  - docker
  
before_install:
  - docker run -it -d -p 5984:5984 klaemo/couchdb:2.0-dev --with-admin-party-please --with-haproxy -n 1

before_script:
  - curl -X GET localhost:5984/_membership
  # https://github.com/klaemo/docker-couchdb/issues/42#issuecomment-169610897
  - curl -X PUT localhost:5984/_node/node1@127.0.0.1/_config/admins/root -d '"password"'
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
